title: "Biovega Services"
description: "Official documentation for Biovega d.o.o. digital services"
url: "https://biovega.github.io"
baseurl: "/biovega.services.docs"

just_the_docs:
  custom_css:
    /assets/CSS/custom.css
