# ===========================================================
# Biovega Services Documentation - Jekyll Configuration
# ===========================================================

title: "Biovega Services"
description: "Official documentation for Biovega d.o.o. digital services"

just_the_docs:
  custom_css:
    /assets/css/custom.css
